import { FileText, Target, Sparkles } from "lucide-react"

export function Hero() {
  return (
    <section className="relative overflow-hidden py-20 md:py-28">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-background to-background" />
      <div className="container mx-auto px-4">
        <div className="mx-auto max-w-3xl text-center">
          <h1 className="text-balance text-4xl font-bold tracking-tight text-foreground md:text-5xl lg:text-6xl">
            Land Your Dream Job with{" "}
            <span className="text-primary">AI-Powered</span> Applications
          </h1>
          <p className="mt-6 text-pretty text-lg text-muted-foreground md:text-xl">
            Upload your resume and job description to get instant keyword
            analysis, match scoring, and a tailored cover letter generated by AI.
          </p>
        </div>

        <div id="features" className="mt-16 grid gap-6 md:grid-cols-3">
          <FeatureCard
            icon={<Target className="h-6 w-6" />}
            title="Keyword Matching"
            description="Identify missing keywords from job descriptions to optimize your resume for ATS systems."
          />
          <FeatureCard
            icon={<FileText className="h-6 w-6" />}
            title="Match Scoring"
            description="Get a clear percentage score showing how well your resume aligns with the job requirements."
          />
          <FeatureCard
            icon={<Sparkles className="h-6 w-6" />}
            title="Cover Letter Generation"
            description="Receive a professionally written cover letter tailored to the specific job and your experience."
          />
        </div>
      </div>
    </section>
  )
}

function FeatureCard({ icon, title, description }) {
  return (
    <div className="group rounded-xl border border-border bg-card p-6 shadow-sm transition-all hover:border-primary/50 hover:shadow-md">
      <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">
        {icon}
      </div>
      <h3 className="mb-2 text-lg font-semibold text-card-foreground">{title}</h3>
      <p className="text-sm text-muted-foreground">{description}</p>
    </div>
  )
}
